"""querys table

Revision ID: e5fcbe07ff1e
Revises: 9804bab371de
Create Date: 2024-07-03 08:25:17.378393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fcbe07ff1e'
down_revision = '9804bab371de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_user_id'))
        batch_op.drop_index(batch_op.f('ix_query_timestamp'))

    op.drop_table('query')
    # ### end Alembic commands ###
